language: node_js
node_js:
  - "node"

cache: bundler

install:
  - npm install
  # - cd client/
  # - npm install
  # - cd ../server/
  # - npm install
  # - cd ..

script:
  - npm run test:unit
  - npm run build
  # - cd client/
  # - npm run build
  # - npm run test
  # - cd ../server
  # - rm -rf public/
  # - npm run build
  # - npm run test