language: node_js
node_js:
  - "node"

cache: bundler

install:
  - cd client/
  - npm install 
  - cd ../server
  - npm install

script:
  - npm run build
  - cd ../client && npm run test:unit
  - npm run build